!function(){var f,l=this&&this.F||function(a,b){function c(){this.constructor=a}for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)};function m(){}m.prototype.onUnavailable=function(){};function p(a){var b=Array.prototype,c=b.toJSON;return c?(delete b.toJSON,a=JSON.stringify(a),b.toJSON=c,a):JSON.stringify(a)}
function q(){this.crossPriority=0;this.largePriority=10;this.syncPriority=100;this.storeType=4;try{if(this.a=self.localStorage)this.a.setItem("ct.ls.k","ct.ls.v"),"ct.ls.v"===this.a["ct.ls.k"]&&(this.isAvailable=!0),this.a.removeItem("ct.ls.k")}catch(a){r(this)}}l(q,m);q.prototype.add=function(a,b){a.locator.key="ct.ls."+a.locator.key;this.update(a,b);return a.locator};q.prototype.remove=function(a,b){var c=this;t(this,function(){return c.a.removeItem(a.key)},function(){return b(a)})};
q.prototype.update=function(a,b){var c=this;t(this,function(){return c.a.setItem(a.locator.key,p(a.c))},function(){return b(a.locator)})};q.prototype.getAll=function(a){var b=this,c=[];t(this,function(){u(b,function(a){c.push({c:JSON.parse(b.a[a]),locator:{key:a,storeType:b.storeType}})});a(c)},function(){return a(c)})};function t(a,b,c){try{b()}catch(d){r(a),setTimeout(function(){return c},0)}}function r(a){a.isAvailable=!1;a.onUnavailable();u(a,function(b){return a.a.removeItem(b)})}
function u(a,b){if(a.a)for(var c in a.a)0===c.indexOf("ct.ls.")&&b(c)}
function v(){var a=this;this.f=[];this.crossPriority=this.syncPriority=0;this.isAvailable=!0;this.largePriority=100;this.storeType=3;try{if(self.indexedDB){var b=function(){return w(a)},c=indexedDB.open("ct.db",2);c.onupgradeneeded=function(b){if(b=x(a,b.target))b.objectStoreNames.contains("ct.db.os")&&b.deleteObjectStore("ct.db.os"),b.objectStoreNames.contains("ct.db.st")||b.createObjectStore("ct.db.st").createIndex("sid","sid",{unique:!1})};c.onsuccess=function(c){var e=a.a;!e&&(e=x(a,c.target))&&
(e.onabort=e.onversionchange=e.onclose=b,a.b=!0,y(a))};c.onerror=c.onblocked=b}}catch(d){w(this)}}l(v,m);function x(a,b){if(b.result.constructor===IDBDatabase)return b.result;w(a);return null}v.prototype.add=function(a,b){a.locator.key="ct.db."+a.locator.key;this.update(a,b);return a.locator};v.prototype.remove=function(a,b){z(this,this.remove,1,[a.key],a,b)};v.prototype.update=function(a,b){z(this,this.update,0,[a.c,a.locator.key],a,b)};
v.prototype.getAll=function(a){var b=this,c=[];if(this.b)try{var d=this.a.transaction("ct.db.st","readonly");d.onabort=d.onerror=d.oncomplete=function(){return a(c)};d.objectStore("ct.db.st").openCursor().onsuccess=function(a){(a=a.target.result)&&a.constructor===IDBCursorWithValue&&(c.push({c:a.value,locator:{key:a.key,storeType:b.storeType}}),a["continue"]())}}catch(e){e.constructor===DOMException&&"InvalidStateError"===e.name&&(this.a.objectStoreNames.contains("ct.db.st")||w(this)),a(c)}else B(this,
this.getAll,[a])};function y(a){var b=setTimeout(function(){clearTimeout(b);var c=a.f.shift();c&&(c.s.apply(a,c.C),y(a))},0)}function w(a){a.isAvailable=a.b=!1;try{a.a.close()}catch(b){}a.a=null;a.onUnavailable()}
function z(a,b,c,d,e,A){var k=e.locator||e;if(!a.b||a.g)B(a,b,[e,A]);else try{a.g=!0;var g=a.a.transaction("ct.db.st","readwrite");g.onabort=g.onerror=function(){D(a);A(k)};g.oncomplete=function(){return D(a)};var n=g.objectStore("ct.db.st");switch(c){case 0:n.put(d[0],d[1]);break;case 1:n["delete"](d[0])}}catch(h){w(a),D(a),A(k)}}function D(a){a.g=!1;y(a)}function B(a,b,c){a.f.push({s:b,C:c})}function E(a,b,c){this.a=a;this.f=b;this.b=c;this.a.registerDispatcher(b)}f=E.prototype;
f.stopSession=function(a,b){this.a.stopSession(a,b||this.b)};f.startSession=function(a,b){this.a.startSession(a,b||this.b)};f.extendSession=function(a,b){this.a.extendSession(a,b||this.b)};f.sendMessages=function(){this.f.dispatched||(this.f.dispatched=!0,this.a.sendMessages())};f.removeMessage=function(a){this.a.removeMessage(a)};f.storeMessage=function(a,b,c,d){return this.a.storeMessage(a,b,c,d)};
function G(a){var b=this;this.j=a;this.g={};this.b=[];this.h=[];this.a={};this.f={};this.l=[];this.m();a.forEach(function(a){return a.onUnavailable=b.m.bind(b)})}f=G.prototype;f.registerDispatcher=function(a){var b=this;a.supportedMessageNames.forEach(function(c){return b.g[c]=a})};f.unregisterDispatcher=function(a){var b=this;a.supportedMessageNames.forEach(function(a){return delete b.g[a]})};f.stopSession=function(a,b){this.a[a]&&(this.extendSession(a,b),delete this.a[a])};
f.startSession=function(a,b){var c=this,d=Date.now();if(!this.a[a]){var e=void 0;this.a[a]=e=H({sid:a,created:d,expires:d+b},1);I(this,e,function(){return delete c.a[a]},!1,!1)}};f.extendSession=function(a,b){var c;if(c=this.a[a]){c.c.item.expires=Date.now()+b;var d=J(this,c.locator);this.a[a]=c;d&&d.update(c,function(){})}};f.storeMessage=function(a,b,c,d){return this.a[a.sid]?(a=H(a,2),I(this,a,function(a){return b(a)},c,d),a.locator):null};f.removeMessage=function(a){K(this,{o:a,D:0})};
f.sendMessages=function(){var a=this,b=0,c=[],d=this.j.filter(function(a){return a.isAvailable});this.h.forEach(function(b){a.g[b.c.item.name]&&a.b.push(b)});d.forEach(function(e){return e.getAll(function(e){c=c.concat(e);if(++b===d.length){e=c;for(var k,g=null,n=0;n<e.length;n++){var h=e[n];if(k=h.c.item){var C=h.c.type;1!==C||a.a[k.sid]||a.f[k.sid]?2===C&&-1===a.b.indexOf(h)&&-1===a.h.indexOf(h)&&a.b.push(h):(g&&g.c.type===C&&(g.c.item.expires=0),a.f[k.sid]=h,a.b.push(h))}g=h}L(a.i.bind(a))}})})};
function H(a,b){return{c:{v:1,type:b,item:a},locator:{storeType:0,key:Date.now()+"."+parseInt(1E6*(Math.random()+1),10)}}}function I(a,b,c,d,e){(a=d&&a.w||e&&a.A||a.B)?(b.locator.storeType=a.storeType,a.add(b,c)):c(b.locator)}function K(a,b){function c(){3>++b.D&&a.l.push(b);L(a.u.bind(a))}var d=b.o,e=J(a,b.o);e?e.remove(d,c):c()}function L(a){var b=setTimeout(function(){clearTimeout(b);a()},0)}
f.i=function(){var a=this,b=this.b.shift();if(b){var c=b.c.item,d=this.g[c.name];(c=(c=this.f[c.sid])&&c.c.item)?c.expires<Date.now()?(delete this.f[c.sid],this.removeMessage(b.locator)):d&&d.isAvailable?d.dispatch({message:b.c.item,locator:b.locator},{defer:function(){a.b.push(b);L(a.i.bind(a))},reject:function(){a.removeMessage(b.locator)},resolve:function(){a.h.push(b)}}):this.h.push(b):this.removeMessage(b.locator);L(this.i.bind(this))}};f.u=function(){var a=this.l.shift();a&&K(this,a)};
function J(a,b){return a.j.filter(function(a){return a.storeType===b.storeType&&a.isAvailable})[0]}f.m=function(){var a=this.j.filter(function(a){return a.isAvailable});this.B=a.filter(function(a){return 0<a.syncPriority}).sort(function(a,c){return c.syncPriority-a.syncPriority})[0];this.A=a.filter(function(a){return 0<a.largePriority}).sort(function(a,c){return c.largePriority-a.largePriority})[0];this.w=a.filter(function(a){return 0<a.crossPriority}).sort(function(a,c){return c.crossPriority-a.crossPriority})[0]};
function M(a,b){void 0===a&&(a=3E4);void 0===b&&(b=window);this.g=a;this.f=-1;this.b=b;this.syncPriority=10;this.largePriority=this.crossPriority=0;this.storeType=2;if(0===this.b.name.length)this.a={},N(this),this.isAvailable=!0;else if("_CT_"===this.b.name.substr(0,4))try{this.a=JSON.parse(this.b.name.substr(4,this.b.name.length));this.isAvailable=!0;var c=Object.keys(this.a);this.f=+c[c.length-1]}catch(d){O(this)}else O(this)}l(M,m);function N(a){a.b.name="_CT_"+p(a.a)}
function O(a){a.isAvailable=!1;a.onUnavailable()}function P(a){if("_CT_"===a.b.name.substr(0,4))return!1;O(a);return!0}M.prototype.add=function(a){if(P(this))return null;if(this.b.name.length>this.g)return O(this),null;a.locator.key=(++this.f).toString();this.a[this.f]=a.c;N(this);return a.locator};M.prototype.remove=function(a){P(this)||(delete this.a[a.key],N(this))};M.prototype.update=function(a){P(this)||(this.a[a.locator.key]=a.c,N(this))};
M.prototype.getAll=function(a){var b=[];if(!P(this))for(var c in this.a)b.push({c:this.a[c],locator:{key:c,storeType:this.storeType}});a(b)};var Q="object"===typeof module&&"object"===typeof module.exports,R=(Q?module.exports.ClickTaleGlobal:self.ClickTaleGlobal)||{};R.persistence={IndexedDbProvider:v,PersistenceClient:E,PersistenceManager:G,LocalStorageProvider:q,WindowNameProvider:M,PersistenceDispatcher:function(a){this.supportedMessageNames=a}};Q?module.exports=R:self.ClickTaleGlobal=R;ClickTaleGlobal.persistence.version="0.1.27";}.call({});
!function(){var h,k=this&&this.Sa||function(a,b){function c(){this.constructor=a}for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)},m={end:0,f:1,a:2,h:3,b:4,0:"end",1:"init",2:"chunk",3:"preinit",4:"exclude"};function aa(){}aa.prototype.a=function(){return!1};
var ba={visitId:3,version:6,screenX:16,screenY:17,browser:18,location:7,projectId:1,visitorId:2,messageId:5,eventIds:21,rotation:27,pageTags:35,pageviewId:4,viewportX:29,viewportY:30,timeOnPage:12,adobeMCVID:33,gaClientId:34,numOfClicks:14,scrollReach:13,appLoadTime:98,interactions:28,jsErrorCount:11,goalOriented:24,engagementTime:9,firstPageview:31,adobeLegacyId:32,discardedTags:36,browserVersion:19,lackOfInterest:23,attentionSplit:26,timeToProcess:100,briefMovement:101,documentReferrer:8,clientTimeStamp:22,
navigationStart:99,domContentLoaded:10,carelessScrolling:25,durationSinceLastVisit:15,3:"visitId",6:"version",16:"screenX",17:"screenY",18:"browser",7:"location",1:"projectId",2:"visitorId",5:"messageId",21:"eventIds",27:"rotation",35:"pageTags",4:"pageviewId",29:"viewportX",30:"viewportY",12:"timeOnPage",33:"adobeMCVID",34:"gaClientId",14:"numOfClicks",13:"scrollReach",98:"appLoadTime",28:"interactions",11:"jsErrorCount",24:"goalOriented",9:"engagementTime",31:"firstPageview",32:"adobeLegacyId",
36:"discardedTags",19:"browserVersion",23:"lackOfInterest",26:"attentionSplit",100:"timeToProcess",101:"briefMovement",8:"documentReferrer",22:"clientTimeStamp",99:"navigationStart",10:"domContentLoaded",25:"carelessScrolling",15:"durationSinceLastVisit"};function n(a,b,c,d){void 0===a&&(a=!1);void 0===b&&(b=!0);void 0===c&&(c=!0);void 0===d&&(d=!1);this.f=a;this.o=b;this.m=c;this.h=d}n.prototype.S=function(a){return{type:this.a,value:this.i(a)}};
function ca(a){n.call(this,!0,!0,!0);this.id=a;this.a=5}k(ca,n);ca.prototype.i=function(){return this.id};var p={error:0,keyup:1,scroll:2,resize:3,unload:4,submit:5,online:6,mouseup:7,offline:8,mousedown:9,mouseover:10,touchstart:11,beforeunload:12,DOMContentLoaded:13,visibilitychange:14,0:"error",1:"keyup",2:"scroll",3:"resize",4:"unload",5:"submit",6:"online",7:"mouseup",8:"offline",9:"mousedown",10:"mouseover",11:"touchstart",12:"beforeunload",13:"DOMContentLoaded",14:"visibilitychange"};
function da(a,b,c,d){var e=this;this.metrics=a;this.config=b;this.h=c;this.reliable=!0;this.f=0;this.b=3;this.c={p:1,2:1,3:1,4:1,5:1,7:1,12:1};a.filter(function(a){return a.f});ea(d,function(a){a.reliable&&a.type!=m[1]&&fa(e)});this.a=ha(this)}function ha(a){return q(a,a.metrics.filter(function(a){return a.f}),3,!0,0)}function ia(a){return q(a,a.metrics.filter(function(a){return a.o}),1,!0,1,!0)}function ja(a){return q(a,a.metrics.filter(function(a){return a.m}),2)}
function ka(a){return q(a,a.metrics.filter(function(a){return a.h}),0)}function q(a,b,c,d,e,f){void 0===d&&(d=!1);void 0===e&&(e=null);void 0===f&&(f=!1);return function(){var g=null===e?++a.f:a.f=e,g=la(a,g,b,c,f);a.b=c;d&&fa(a);return g}}function la(a,b,c,d,e){var f=a.h(b);c=c.concat([f]).map(function(a){return a.S(d)}).filter(function(b){return b.value||a.c[b.type]});return{id:b,reliable:e,type:m[d],metrics:c}}
function fa(a){switch(a.b){case 3:a.a=ia(a);break;case 1:a.a=ja(a);break;case 2:a.a=ka(a)}}da.prototype.da=function(){return m[this.b]};function ma(a,b,c,d){n.call(this,a,b,c,d)}k(ma,n);function r(a){return{value:a,encoded:decodeURIComponent(a)!==a}}function na(a){return{host:r(a.host),protocol:r(a.protocol.replace(":","")),hash:r(a.hash),search:{value:a.search?"?"+encodeURIComponent(decodeURIComponent(a.search.substring(1))):"",encoded:!0},pathname:r(a.pathname)}}
function u(a,b){n.call(this,!0,!0,!1,!1);this.c=!1;this.g=!0;this.a=7;a!==b.location&&(a.hash=a.hash||"",a.search=a.search||"",a.href=a.protocol+"//"+a.host+a.pathname+a.search+a.hash);this.j=a.href;this.b=na(a)}k(u,ma);u.prototype.i=function(){return this.g||this.c?(this.g=!1,this.j):this.b};u.prototype.dispose=function(){this.c=!0};function oa(a){n.call(this,!1,!1,!1,!0);this.b=a;this.a=36}k(oa,n);
oa.prototype.i=function(a){var b=[],c=pa(this.b),d;for(d in c)b.push({type:parseInt(d),value:c[d]});return b.length?0==a?b.map(function(a){return a.type+"\v"+a.value}).join("\v"):b:null};function v(a,b,c){n.call(this,!1,!1,!1,!0);this.g=a;this.c=!1;this.Z();a.bind(this.ca(),this.ma());a=this.ja.bind(this);var d={K:{}};w(b.a,c.metrics.interestInterval,d)&&!d.K.done&&d.K.ba.push(a)}k(v,n);v.prototype.ja=function(){this.c=!0};
function qa(a){var b=a.target;a=p[a.type];return 5===a?!0:7===a&&"href"in b}v.prototype.Z=function(){};function x(a,b,c){v.call(this,a,b,c);this.b=!0;this.a=23}k(x,v);x.prototype.ca=function(){return this.g.g.concat([5])};x.prototype.ma=function(){var a=this;return function(b){a.c?a.b=!1:qa(b)&&(a.b=!1)}.bind(this)};x.prototype.i=function(){return this.b};function ra(){this.type=3;this.V=[1,2]}function y(){}y.prototype.X=function(a){this.c=a;return this};y.prototype.b=function(){this.c()};
function sa(a){this.a=a}k(sa,y);function ta(a){this.a=a;this.f=this.b.bind(this)}k(ta,sa);ta.prototype.start=function(){this.a.bind([0],this.f)};ta.prototype.D=function(){ua(this.a,[0],this.f)};function z(a,b,c,d){void 0===b&&(b=!1);void 0===c&&(c=!0);void 0===d&&(d=!0);n.call(this,b,c,d,!!(a&&a.metrics&&a.metrics.enableOptionalEndMetrics));this.f=b;this.o=c;this.m=d}k(z,n);function A(a,b){z.call(this,b);this.j=a;this.j.bind(this.c.bind(this))}k(A,z);A.prototype.S=function(){return{type:this.a,value:this.i()}};
function B(a,b){z.call(this,b,!1,!0,!0);this.c=a;this.j=/^https?:\/\/((s2?)|(cdn(a|poc|ssl)*))\.clicktale\.net\/.+\.js/i;this.a=11;this.b=0;this.c.bind([0],this.g.bind(this))}k(B,z);B.prototype.g=function(a){this.j.test(a.filename)||this.b++};B.prototype.i=function(){return this.b};function C(a,b){A.call(this,a,b);this.b=0;this.a=25}k(C,A);C.prototype.i=function(){return this.b};C.prototype.c=function(a){a.direction.P&&1E3>a.H&&this.b++};function D(){return(new Date).getTime()}
function va(a){var b=Array.prototype,c=b.toJSON;return c?(delete b.toJSON,a=JSON.stringify(a),b.toJSON=c,a):JSON.stringify(a)}function wa(a){var b=null;try{b=a()}catch(c){}return b}var xa=Math.pow(2,53)-1;function E(a,b){z.call(this,b);this.g=a;this.config=b;this.a=28;this.j=this.c=0;this.u=1;this.Qa=2;this.wa=4;this.touchMouseIgnoreTime=this.config.metrics.touchMouseIgnoreTime;this.b=0;this.g.bind([1],this.Ra.bind(this));this.g.bind([11],this.sa.bind(this));this.g.bind([9],this.J.bind(this))}
k(E,z);E.prototype.Ra=function(){this.b|=this.Qa};E.prototype.sa=function(){this.b|=this.wa;this.c=Date.now()};E.prototype.J=function(){var a=this,b=this.b&this.u;this.j=Date.now();b||this.c&&!(Math.abs(this.j-this.c)>this.touchMouseIgnoreTime)||(this.c=0,setTimeout(function(){a.c||(a.b|=a.u)},this.touchMouseIgnoreTime))};E.prototype.i=function(){return this.b};
function ya(){var a,b;void 0===a&&(a=window);void 0===b&&(b=document);this.a=a;this.f=b;this.b=/ (\w+)(?:\/([\w\.]+))? (?:(\([^\)]+\)) )?/img;this.userAgent=za(this," "+a.navigator.userAgent+" ")}
function za(a,b){for(var c=a.a.XMLHttpRequest,d={},e;e=a.b.exec(b);)d[e[1]]={value:e[2],extra:e[3]},a.b.lastIndex--;if(e=/Mobi|Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini|CriOS|bada/i.test(b))try{a.f.createEvent("TouchEvent"),e=!0}catch(t){e=!1}var f=e;e={is:{I:f},aa:{version:0}};var g=e.aa,l=d.Mozilla&&d.Mozilla.extra?d.Mozilla.extra:null;e.supports={sendBeacon:!!a.a.navigator.sendBeacon,Ta:c&&"withCredentials"in new XMLHttpRequest,Ba:Aa()};if(d.Opera)return g.name="Opera",g.type=
1,(d=/Version\/(\d+)/i.exec(b))&&d[1]&&(g.version=Number(d[1])),e;if(d.Edge)return g.type=0,g.name="Edge",g.version=parseInt(d.Edge.value),e.is.I=f||-1!==b.indexOf("Windows Phone; "),e;if(l&&(c=void 0,c=l.indexOf("MSIE "),-1<c+l.indexOf("; Trident/")&&(c=-1!==c?c:l.indexOf("; rv:"),-1!==c)))return g.name="IE",g.type=7,g.version=parseFloat(l.substr(c+5,3)),e.is.I=f,e;if(d.Firefox&&d.Firefox.value)return g.type=5,g.name="Firefox",g.version=parseFloat(d.Firefox.value),e.is.I=f||l&&-1!==l.indexOf("Android; "),
e;if(c=/Firefox\/(\d+)/i.exec(b))return g.type=5,g.name="Firefox",c[1]&&(g.version=Number(c[1])),e;if(d.Chrome&&d.Chrome.value||d.CriOS&&d.CriOS.value)return g.type=3,g.name="Chrome",g.version=parseFloat(d.Chrome?d.Chrome.value:d.CriOS.value),e.is.I=f||d.CriOS||l&&-1!==l.indexOf("; Android "),e;d.Safari&&(g.name="Safari",l&&-1===l.indexOf("Windows")&&d.Version&&d.Version.value&&(g.type=4,g.version=parseFloat(d.Version.value),e.is.I=f));return e}
function Aa(){var a=Function.prototype;if(!a||!a.bind)return!1;a=Date.prototype;if(!(Date.now&&a&&a.toISOString&&a.toJSON))return!1;a=Array.prototype;return!!(a&&a.every&&a.filter&&a.forEach&&a.indexOf&&a.lastIndexOf&&a.map&&a.some&&a.reduce&&a.reduceRight&&Array.isArray)}function Ba(a){this.f=a;this.a=[];this.a.push(this.Ha);this.a.push(this.Ia);this.a.push(this.Ca);this.a.push(this.Fa);this.a.push(this.Ga)}h=Ba.prototype;h.Ia=function(a){return a.direction.P&&350>a.F.A&&650>=a.F.duration&&.5<a.speed};
h.Fa=function(a){return a.direction.P&&100>a.F.A&&300>=a.F.duration};h.Ga=function(a){return a.direction.P&&30>a.F.A};h.Ca=function(a){return 1===a.U};h.Ha=function(a){return 0===a.direction.value};
function Ca(a,b,c){this.userAgent=b;this.g=c;this.U=this.h=0;this.f=[];this.c=[];this.o=[];this.f.push(this.ra.bind(this));this.f.push(this.za.bind(this));this.c.push(this.Ea.bind(this));this.c.push(this.Pa.bind(this));this.u=new Ba(this.xa.bind(this));a.bind([2],this.Ka.bind(this));a.bind([3],this.Ja.bind(this))}h=Ca.prototype;h.bind=function(a){this.o.push(a)};
h.Ka=function(){var a=Da(this);clearTimeout(this.m);this.a&&(a.H=a.time-this.a.time,a.A=a.B-this.a.B,a.direction=a.A/(Math.abs(a.A)||1));var b;a:{b=0;for(var c=this.c;b<c.length;b++)if((0,c[b])(a)){b=!1;break a}b=!0}if(b){a:{b=0;for(c=this.f;b<c.length;b++)if((0,c[b])(a)){b=!0;break a}b=!1}b&&(Ea(this),a.direction=0,a.H=a.A=0);this.b||(this.b=a);this.a=a;this.U++;Fa(this)}};h.Ja=function(){this.h=Date.now()};h.xa=function(a){this.o.forEach(function(b){return b(a)})};
h.Ea=function(a){return 70>=a.time-this.h?(this.h=0,!0):!1};h.Pa=function(a){return this.userAgent.is.I&&this.a?20>a.time-this.a.time:!1};h.za=function(a){return this.a?0===this.a.direction?0>(this.a.B-this.b.B)*a.direction:0==a.direction+this.a.direction:!1};h.ra=function(a){return this.a&&1E3<=a.time-this.a.time?!0:!1};function Fa(a){a.m=setTimeout(function(){clearTimeout(a.m);a.ra(Da(a))&&Ea(a)},1E3)}function Da(a){return{H:0,A:0,time:Date.now(),B:a.g.pageYOffset,direction:0}}
function Ea(a){if(a.b){var b=a.u,c=a.b,d=a.a||a.b,e=d.B-c.B,c={qa:0,H:0,speed:0,U:a.U,start:{time:c.time,B:c.B},end:{time:d.time,B:d.B},F:{A:Math.abs(e),duration:d.time-c.time},direction:{value:0,P:!1}};c.speed=c.F.A/c.F.duration||1;c.direction.value=e/(c.F.A||1);b.b&&(c.qa=b.b.qa+1,c.H=c.start.time-b.b.end.time,c.direction.P=0!==c.direction.value&&c.direction.value!==b.b.direction.value);a:{e=0;for(d=b.a;e<d.length;e++)if((0,d[e])(c)){e=!1;break a}e=!0}e&&(b.b=c,b.f(c));a.a=a.b=null;a.U=0}}
h.dispose=function(){!this.j&&(this.j=!0)&&Ea(this)};function Ga(){}function Ha(a){return va(a).split(",").map(function(a){return a.replace(/'/g,"''").replace(/[\"]/g,"'")}).join("|")}function Ia(a){a=a.replace(/[{}]/g,"").split("|").map(function(a){a=a.split(":");var c=a[1];a[0]=a[0].replace(/'/g,'"');isNaN(a[1])&&(a[1]=('"'+c.substring(1,c.length-1)+'"').replace("''","'"));return a.join(":")});return JSON.parse("{"+a.join(",")+"}")}function F(){n.call(this,!1,!0,!1)}k(F,n);
function Ja(){F.call(this);this.b=null;this.a=34;var a=window.ga;a&&"function"===typeof a.getAll&&(a=a.getAll())&&a.length&&"function"===typeof a[0].get&&(this.b=a[0].get("clientId"))}k(Ja,F);Ja.prototype.i=function(){return this.b};function Ka(){}Ka.prototype.a=function(a){var b={};a.forEach(function(a){return b[ba[a.type]]=a.value});return va(b)};Ka.prototype.b=function(){return null};function G(){}G.prototype.resolve=function(){};G.prototype.reject=function(){};
function H(a,b,c){this.b=a;this.app=b;this.f=c}function La(a,b,c){void 0===c&&(c=0);a.reset(c);a.b.O.resolve(b)}function I(a,b,c){void 0===c&&(c=0);a.reset(c);a.app.fa()&&setTimeout(function(){a.b.O.reject(b)},a.b.waitInterval)}function Ma(a,b){var c=b.message.data;return a.f?a.f.a(c):c}function J(a,b,c,d,e){void 0===e&&(e="POST");H.call(this,a,b,c);this.xhrTimeout=d;this.h=e;this.a=new XMLHttpRequest;(a=self.ClickTaleMonitor.Settings.get())&&a.xhrCreatedCallback(this.a)}k(J,H);
J.prototype.send=function(a,b){var c=this;try{var d=this.a,e="GET"===this.h;e&&(a+="&"+Ma(this,b));d.open(this.h,a);d.timeout=this.xhrTimeout;d.setRequestHeader("Content-Type","text/plain");this.a.onreadystatechange=function(){4===d.readyState&&(200===d.status?La(c,b):I(c,b))};d.onload=function(){return La(c,b)};d.onerror=d.ontimeout=d.onabort=function(){return I(c,b)};if(e)d.send();else{var f=Ma(this,b);d.send(f)}}catch(g){I(this,b)}};
J.prototype.reset=function(){var a=this.a;a&&(a.onabort=a.ontimeout=a.onerror=a.onload=a.onreadystatechange=null)};function Na(a){for(var b=arguments.length,c,d,e,f,g,l=1;l<b;l++)if(c=arguments[l])for(d in c)e=a[d],f=c[d],a!==f&&(f&&(Oa(f)||(g=Array.isArray(f)))?g?(g=!1,a[d]=f.slice()):(e=e&&Oa(e)?e:{},a[d]=Na(e,f)):void 0!==f&&(a[d]=f));return a}
function Oa(a){return"object"!==(null==a?a+"":"object"===typeof a||"function"===typeof a?Pa[Qa.call(a)]||"object":typeof a)||a.nodeType||a===window||a.constructor&&!Ra.call(a.constructor.prototype,"isPrototypeOf")?!1:!0}var Pa={},Qa=Pa.toString,Ra=Pa.hasOwnProperty;
function Ta(a,b,c,d,e,f){this.config=c;this.c=d;this.cookie="ctm";this.f=!1;a:{b=this.config.identification.cookie;a=-2;if(b){if(b.currentDomain){this.b="";break a}if(b.domain){this.b=b.domain;break a}}b=document.location.hostname;-1<b.indexOf(".co.")&&(a=-3);this.b=b.split(".").slice(a).join(".")}Ua(this,f)}
function Ua(a,b){var c=!1,d=Va(),e=!b&&ClickTaleMonitor&&ClickTaleMonitor.pgv;d&&(c=Wa(a,d,function(){var b=D();if(0===d.vst||a.c.W(d))a.f=!0,d.vst=K(),d.lvst=a.h=Math.round((b-d.intr)/6E4);d.intr=b;a.h=d.lvst;d.pgv=e||K();return d}));c||(a.f=!0,L(a,a.a={pgv:e||K(),vst:K(),vstr:K(),intr:D()}));a.identification={ka:a.a.vst,Y:a.a.vstr,L:a.a.pgv,Ua:a.a.lvst,lastModified:a.a.intr}}
function Va(){var a,b=0,c=0,d=0,e=!1,f=document.cookie,g=f.split(";");a="ctm=";for(var l=0;l<g.length;l++){var t=g[l];0===t.trim().indexOf(a)&&(-1<t.trim().indexOf("'v':1")?(b=c+t.length,d=c+t.split("=")[0].length+1,e=!0):Xa(a.substring(0,a.length-1),"",-1,void 0));c+=t.length+1}if(a=e?f.substring(d,b):null)try{return Ia(a)}catch(Mc){}return null}function Wa(a,b,c){return Ya(b)?(b=c?c(b):b,L(a,b),a.a=b,!0):!1}
function Ya(a){var b=["vst","pgv","vstr","intr"];"lsvt"in a&&b.push("lvst");return b.every(function(b){b=a[b];return!isNaN(parseFloat(b))&&isFinite(b)})}function L(a,b){b.v=1;Xa(a.cookie,Ha(b),a.config.identification.expirationDays,a.b)}function Za(a,b,c,d){var e=this;this.l=b;this.config=c;this.app=d;b=[4];var f=this.dispose.bind(this);c.onEnd.useOnBeforeUnload&&b.push(12);setTimeout(function(){return f(!1,!0)},c.identification.visitTimeSpan);a.bind(b,function(){return e.dispose()})}
Za.prototype.dispose=function(a,b){var c=this.a;c.a=ka(c);this.l.dispose(a);if(b){var c=this.l.resolve("IdentificationService"),d=this.config,e=this.app,f=c.identification,g=d.transport.url.replace("/monitor","/visitended"),d=new J({waitInterval:0,O:new G},e,null,d.transport.xhrTimeout),e={message:{data:va({projectId:e.oa(),visitorId:f.Y,visitId:f.ka})}};d.send(""+g,e);g=Va();L(c,c.a={pgv:null!==g?g.pgv:K(),vst:0,vstr:null!==g?g.vstr:K(),intr:D()})}this.app.la()};Za.prototype.ia=function(){this.dispose(!0)};
function $a(a,b,c){v.call(this,a,b,c);this.config=c;this.j=!1;this.a=24}k($a,v);h=$a.prototype;h.Z=function(){var a=this;v.prototype.Z.call(this);this.b=function(b){!a.c&&qa(b)&&(a.u=Date.now())}.bind(this)};h.ja=function(){v.prototype.ja.call(this);ua(this.g,this.ca(),this.b)};h.ca=function(){return[7,5]};h.ma=function(){return this.b};h.i=function(){return this.j};h.dispose=function(){Date.now()-this.u<this.config.metrics.goalOrientedCloseInterval&&(this.j=!0)};function M(){}M.prototype.a=function(a){return ab(a)};
M.prototype.b=function(a){return a.split("&").map(function(a){a=a.split("=");var c=a[1],d=Number(c);return{type:Number(a[0]),value:isNaN(d)?"true"===c?!0:"false"===c?!1:decodeURIComponent(c):d}})};function ab(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];d&&b.push(d.type+"="+encodeURIComponent(d.value))}return b.join("&")}function bb(a,b,c,d){a=new a({waitInterval:0,O:new G},d,null,b.transport.xhrTimeout);c={message:{data:ab([{type:"p",value:c}])}};a.send(b.transport.url+"?t="+m[4],c)}
function cb(a){n.call(this,!1,!0,!1);this.b=a;this.a=31}k(cb,n);cb.prototype.i=function(){return this.b.f};function db(){}function K(){var a=window.crypto||window.msCrypto;if(a){var b=new Uint32Array(2);a.getRandomValues(b);for(var a=b[0]&2097151,c=32;0<c--;)a=2*a;b=a-1+b[1];return-1===b?0:b}return Math.floor(Math.random()*xa)}function N(a){z.call(this,a);this.c=!1;this.b=[];this.a=21}k(N,z);N.prototype.i=function(){return this.b.length?this.b:null};N.prototype.D=function(){this.c=!1};
N.prototype.start=function(){this.c=!0};N.prototype.X=function(a){this.g=a;return this};function eb(a){n.call(this,!1,!1,!0,!0);this.g=a;this.c=this.b=0;this.a=9;this.g.bind(a.g,this.j.bind(this))}k(eb,n);eb.prototype.j=function(){var a=Date.now();this.c&&(this.b+=Math.min(2E4,a-this.c));this.c=a};eb.prototype.i=function(){return this.b};function fb(){}fb.prototype.a=function(a){return this.f.a(a)};fb.prototype.b=function(a){this.f=a};function O(){}k(O,fb);
O.prototype.a=function(a){var b=a.cmpn,c=self.URLSearchParams,c=c?c.prototype.get.bind(new c(location.search)):this.h;return(c=gb(c)())&&c!==b?(a.cmpn=c,!0):this.c.a(a)};function gb(a){return function(){return decodeURIComponent(a("utm_campaign")||"")}}O.prototype.h=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");return(a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(self.location.search))?decodeURIComponent(a[1].replace(/\+/g," ")):""};O.prototype.b=function(a){this.c=a};
function hb(a){this.config=a}k(hb,fb);hb.prototype.a=function(a){return D()-a.intr>=this.config.identification.visitTimeSpan?!0:this.f.a(a)};hb.prototype.b=function(a){this.f=a};function ib(){}ib.prototype.W=function(a){return this.a.a(a)};function jb(a){this.config=a;var b=new O,c=new aa;this.a=new hb(a);this.a.b(b);b.b(c)}k(jb,ib);jb.prototype.W=function(a){return this.a.a(a)};function kb(a){F.call(this);this.b=a;this.a=15}k(kb,F);kb.prototype.i=function(){return this.b.h};
function lb(a){n.call(this,!1,!0,!1,!1);this.c=a;this.a=8;a&&(a=document.createElement("A"),a.href=this.c,this.b=na(a))}k(lb,ma);lb.prototype.i=function(){return this.b||this.c};function mb(a,b){ClickTaleGlobal.persistence.PersistenceDispatcher.call(this,a);this.supportedMessageNames=a;this.ha=b}k(mb,ClickTaleGlobal.persistence.PersistenceDispatcher);mb.prototype.dispatch=function(a,b){this.dispatched=!0;this.ha(a,b)};function nb(a){F.call(this);this.timing=a;this.a=10}k(nb,F);
nb.prototype.i=function(){return this.timing.domContentLoadedEventEnd-this.timing.navigationStart};function P(a){this.m=this.o=this.h=this.f=!1;this.a=xa;this.navigationStart=a.navigationStart;this.b=this.c=this.a=0}P.prototype.S=function(){return{value:{sum:this.c,max:0,min:this.a,count:this.b},type:this.G()}};function ob(){n.call(this,!1,!0,!0,!1);this.a=22}k(ob,n);ob.prototype.i=function(){return D()};function pb(a,b,c){this.b=a;this.a=c}
pb.prototype.send=function(a,b){var c=b.message.data,c=this.a?this.a.a(c):c;navigator.sendBeacon(a+"&"+c)?this.b.O.resolve(b):this.b.O.reject(b)};function qb(a){F.call(this);this.a=19;this.userAgent=a.userAgent}k(qb,F);qb.prototype.i=function(){return this.userAgent.aa.version};function rb(a,b,c){H.call(this,a,b,c);this.h=0;this.a={}}k(rb,H);
rb.prototype.send=function(a,b){var c=this,d=Ma(this,b),e=new Image,f=++this.h;this.a[f]=e;e.onload=function(){return La(c,b,f)};e.onerror=function(){return I(c,b,f)};e.src+=a+"&"+d+"&r="+(new Date).getTime()};rb.prototype.reset=function(a){delete this.a[a]};function sb(a){F.call(this);this.a=18;this.userAgent=a.userAgent}k(sb,F);sb.prototype.i=function(){return this.userAgent.aa.name};function tb(a){P.call(this,a)}k(tb,P);tb.prototype.G=function(){return 101};
function Q(a){n.call(this,!0,!0,!0,!0);this.identification=a.identification}k(Q,n);function ub(a){Q.call(this,a);this.a=2;this.h=this.f=!1}k(ub,Q);ub.prototype.i=function(){return this.identification.Y};function vb(a){n.call(this,!1,!0,!1,!0);this.app=a;this.a=98}k(vb,n);vb.prototype.i=function(){return this.app.na()};function wb(){F.apply(this,arguments);this.a=29}k(wb,F);wb.prototype.i=function(){return self.innerWidth|0};function R(){n.call(this,!1,!0,!0,!0);this.retries=5}k(R,n);
R.prototype.b=function(a,b,c,d){for(var e=document.cookie.split(";"),f=0,g=e.length,l=void 0;f<g;f++)if(l=e[f].trim().match(a))return xb(l[c],b,d);return null};function xb(a,b,c){a=a||"";return(b=(decodeURIComponent(a)||a).match(b))?b[c]:null}R.prototype.i=function(){var a=this.g;!a&&this.retries--&&(this.g=a=this.c());return a};function yb(){R.apply(this,arguments);this.a=33}k(yb,R);
yb.prototype.c=function(){return wa(function(){var a=self.s;return(a=a&&a.visitor)&&a.getMarketingCloudVisitorID()})||R.prototype.b.call(this,/AMCV_(.*)AdobeOrg\=(.*)/,/MCMID\|(.*?)\|/,2,1)};function zb(){F.apply(this,arguments);this.a=6}k(zb,F);zb.prototype.i=function(){return"1.3.61"};function Ab(){R.apply(this,arguments);this.a=32}k(Ab,R);
Ab.prototype.c=function(){var a=/s_fid\=(.*)/,b=/.+?\|([^\[|]+)/;return wa(function(){var a=self.s,d=a&&a.c_r;return d&&xb(d("s_vi"),b,1)||a&&a.fid||d&&d("s_fid")})||R.prototype.b.call(this,/s_vi\=(.*)/,b,1,1)||R.prototype.b.call(this,a,a,0,1)};function Bb(a){this.h=this.f=!1;this.o=this.m=!0;this.c=0;this.b=!1;this.a=0;this.navigationStart=a.navigationStart}function Cb(a){var b=Date.now();a.b&&(a.a+=b-a.c,a.c=b)}
Bb.prototype.S=function(){Cb(this);return{type:this.G(),value:Date.now()-this.navigationStart-this.a}};function Db(a,b){Bb.call(this,b);this.g=a;this.h=!0;this.g.bind([14],this.j.bind(this))}k(Db,Bb);Db.prototype.G=function(){return 12};Db.prototype.j=function(){document.hidden?(this.b=!0,this.c=Date.now()):(Cb(this),this.b=!1)};function Eb(a){F.call(this);this.userAgent=a;this.b=0;this.a=27}k(Eb,F);Eb.prototype.i=function(){this.userAgent.is.I&&(this.b=self.innerHeight>=self.innerWidth?1:2);return this.b};
function Fb(){F.apply(this,arguments);this.a=16}k(Fb,F);Fb.prototype.i=function(){return screen.width};function Gb(a){n.call(this,!1,!0,!0,!1);this.b=a;this.a=1}k(Gb,n);Gb.prototype.i=function(){return this.b};function Hb(a){Q.call(this,a);this.a=4}k(Hb,Q);Hb.prototype.i=function(){return this.identification.L};function Ib(a){F.call(this);this.timing=a;this.a=99}k(Ib,F);Ib.prototype.i=function(){return this.timing.navigationStart};function Jb(){this.b=[];this.f=[];this.a=[]}
function ea(a,b){a.f.push(b)}function Kb(a,b){a.b.push(b)}Jb.prototype.resolve=function(a){Lb(a,this.a);Lb(a,this.f)};Jb.prototype.reject=function(a){Lb(a,this.a);Lb(a,this.b)};function Lb(a,b){b.forEach(function(b){return b(a)})}function Mb(){this.type=4;this.V=[2,0]}function Nb(a,b){A.call(this,a,b);this.g=this.b=0;this.a=26}k(Nb,A);Nb.prototype.i=function(){return this.b/(this.g||1)||void 0};Nb.prototype.c=function(a){1E3<=a.H&&(this.g++,this.b+=a.H)};
function Ob(a){z.call(this,a);this.a=this.G()}k(Ob,z);Ob.prototype.D=function(){};Ob.prototype.start=function(){};Ob.prototype.X=function(){return this};function Pb(a,b,c,d){J.call(this,a,b,c,d,"GET")}k(Pb,J);function Qb(a){Q.call(this,a);this.a=3}k(Qb,Q);Qb.prototype.i=function(){return this.identification.ka};var Rb=/function ([^\(]+)/;
function Sb(a,b){var c;if(!(c=b)){var d;if("string"===typeof a)d=a;else{if(!((c=a.name)||(c=a.toString().match(Rb),c=c&&0<c.length&&c[1]))){c=[];var e=a.prototype;for(d in e)c.push(d);c=c.join("")}d=c}c=d}this.a=c}Sb.prototype.toString=function(){return this.a};function Tb(a){P.call(this,a)}k(Tb,P);Tb.prototype.G=function(){return 100};function Ub(){}function S(a,b,c){a[b.toString()]=c}function w(a,b,c){return(a=a[b.toString()])?(c.K=a,!0):!1}function Vb(a){this.R=a}k(Vb,Wb);
function Xb(a,b){1!==a.N&&(a.T=b);0===a.C&&b.dispose&&a.l.a.push(b);a.ea&&a.ea(a.l,b)}function Yb(a){var b=new Vb(a.R);b.C=a.C;b.N=a.N;b.T=a.T;b.l=a.l;b.ea=a.ea;return b}function T(){this.a=[];this.b=new Ub;var a=Yb({T:this,R:function(a){return a},l:this,C:1,N:0});S(this.b,new Sb(T),a)}T.prototype.dispose=function(a){for(;0<this.a.length;)this.a.shift().dispose(a)};function U(a,b,c){return Zb(a,b,null,c)}function $b(a,b,c){a=Zb(a,Object.getPrototypeOf(c).constructor,b,null);a.N=0;a.C=1;Xb(a,c)}
function Zb(a,b,c,d){b=new Sb(b,c);d=Yb({l:a,R:d,N:0,C:0});S(a.b,b,d);return d}T.prototype.resolve=function(a,b,c,d,e){return this.f.apply(this,[a,null,b,c,d,e])};T.prototype.f=function(a,b,c,d,e,f){var g;g=Array.prototype.slice.call(arguments,2);var l,t=ac(this,a,b);t?(l=t.T,l||(g=g||[],g.splice(0,0,t.l),l=t.R.apply(null,g),Xb(t,l)),g=l):g=null;return g};
function bc(a,b){var c,d=ac(a,b,null);return d?function(a,b,g,l){a=[d.l,a,b,g,l];c=d.T;c||(c=d.R.apply(null,a),Xb(d,c));return c}:function(){return null}}function ac(a,b,c){var d;b=new Sb(b,c);c={};w(a.b,b,c)&&(d=c.K);return d}function Wb(){}function cc(a){a.N=1;return a}
function V(a,b,c,d){var e=this;this.m=a;this.config=b;this.app=c;this.w=d;this.f=0;this.a=1;this.h=!1;this.maxFetchInterval=this.config.metrics.maxFetchInterval;ea(this.w,function(){return dc(e)});Kb(this.w,function(){return dc(e)})}k(V,y);V.prototype.start=function(){var a=this;ec(this.m,function(){return a.b()})};function dc(a){var b=a.h?a.maxFetchInterval:fc(a);a.D();a.app.fa()&&(a.o=setTimeout(function(){a.b();dc(a)},b))}V.prototype.D=function(){clearTimeout(this.o)};V.prototype.dispose=function(){this.D()};
function fc(a){var b=a.f+a.a,c=1E3*b;if(c>a.maxFetchInterval)return a.h=!0,a.maxFetchInterval;a.f=a.a;a.a=b;return c}function gc(a,b,c,d,e,f){var g=this;this.c=a;this.o=b;this.f=c;this.m=d;this.ha=e;this.h=f;this.b=0;b.forEach(function(a){return a.X(g.a.bind(g)).start()});this.f.bind([6,8],function(){hc(g,function(a){return navigator.onLine?a.start():a.D()})})}
gc.prototype.a=function(){var a=this.m.a(),b=this.c.S().value;b>this.b&&(this.b=b,b=this.h,b.a.intr=b.identification.lastModified=D(),L(b,b.a));this.ha.W(a.metrics,{id:a.id,type:a.type,reliable:a.reliable})};gc.prototype.dispose=function(a){a||this.a();hc(this,function(a){return a.D()})};function hc(a,b){a.o.forEach(function(a){return b(a)})}
function ic(a,b){var c=this;void 0===b&&(b=[]);n.call(this,!1,b.some(function(a){return-1<a.V.indexOf(1)}),!0,b.some(function(a){return-1<a.V.indexOf(0)}));this.g=b;this.b={};this.c={};this.a=this.G();this.maxTagsOnEnd=a.metrics.maxTagsOnEnd;this.j=a.metrics.maxPageTagLength;this.J=a.metrics.pageTagRedundancy;this.u=a.metrics.maxPageTagsPerPage;b.forEach(function(a){c.c[a.type]=[]})}k(ic,n);function pa(a){var b={},c;for(c in a.c){var d=a.c[c].length;d&&(b[c]=d)}return b}
function jc(a,b,c,d){if("number"===typeof b&&"number"===typeof c&&"string"===typeof d){var e=a.g.filter(function(a){return a.type==c})[0];e&&kc(a,b,c,d,e)}}h=ic.prototype;h.D=function(){};h.start=function(){};h.X=function(){return this};
h.i=function(a){var b=this,c=Object.keys(this.b).map(function(a){return b.b[a]}).filter(function(b){return-1<b.Da.V.indexOf(a)&&0<b.Oa--}).map(function(a){return a.tag});return c.length?0==a?(c.splice(this.maxTagsOnEnd),c.map(function(a){return a.id+"\v"+a.type+"\v"+a.value}).join("\v")):c:null};function kc(a,b,c,d,e){var f=d.slice(0,a.j);d=[b,c,f].join("|");a.b[d]||(Object.keys(a.b).length>=a.u?(a=a.c[c],0>a.indexOf(d)&&a.push(d)):a.b[d]=new lc(e,{id:b,type:c,value:f},a.J))}h.G=function(){return 35};
function lc(a,b,c){this.Da=a;this.tag=b;this.Oa=c}function mc(a){var b=this;this.a=new Ub;a.forEach(function(a){return nc(b,a)})}function nc(a,b){S(a.a,b,{ba:[],done:!1});setTimeout(function(){return a.done(b)},b)}mc.prototype.done=function(a){this.a[a.toString()]&&(a=this.a[a],a.ba.forEach(function(a){return a()}),a.ba=null,a.done=!0)};function oc(){}
function Xa(a,b,c,d){var e="";c&&(e=new Date,e.setTime(e.getTime()+864E5*c),e="; expires="+e.toUTCString());document.cookie=a+"="+b+e+"; path=/;"+(d?" domain="+d+";":"")}function W(){this.h=!1;this.o=[];this.m=this.j.bind(this);this.b=this.J.bind(this);this.a=new Ub;this.g=[10,7,1,2,3,11];this.c=[2,3,6,8,12,4];this.f=[9,10,7,1,14,5,11];pc(this)}
function pc(a){a.f.concat(a.c).concat([13]).forEach(function(b){a.a[b]=[]});qc(a);(a.h=/complete|interactive/.test(document.readyState))||document.addEventListener("DOMContentLoaded",function(){return setTimeout(a.m,0)},!1)}W.prototype.bind=function(a,b){rc(this,a,b)};function ua(a,b,c){b.forEach(function(b){if(a.a){b=a.a[b];var e=b.indexOf(c);-1<e&&b.splice(e,1)}})}
function rc(a,b,c){var d;void 0===d&&(d=!1);var e=d?function(a){return a.splice(0,0,c)}:function(a){return a.push(c)};b.forEach(function(b){return e(a.a[b])})}W.prototype.J=function(a){this.a[p[a.type]].forEach(function(b){return b(a)})};W.prototype.dispose=function(){this.a=null;sc(this)};function ec(a,b){a.h?b():a.o.push(b)}W.prototype.j=function(a){this.h=!0;this.o.forEach(function(b){return b(a)});document.removeEventListener("DOMContentLoaded",this.m,!1)};
function qc(a){function b(a){return a.addEventListener}tc(b,window,a.c,a.b);tc(b,document,a.f,a.b);a.a[0]=[];var c=a.u=window.onerror;window.onerror=function(b,e,f,g,l){c&&c(b,e,f,g,l);a.b({filename:e,type:p[0]})}}function sc(a){function b(a){return a.removeEventListener}tc(b,window,a.c,a.b);tc(b,document,a.f,a.b);window.onerror=a.u}function tc(a,b,c,d){c.forEach(function(c){c=p[c];a(b).apply(b,[c,d,!1])})}function uc(a,b,c){ClickTaleGlobal.persistence.PersistenceClient.call(this,a,b,c)}k(uc,ClickTaleGlobal.persistence.PersistenceClient);
uc.prototype.sendMessages=function(){ClickTaleGlobal.persistence.PersistenceClient.prototype.sendMessages.call(this)};
function vc(a,b,c,d,e,f,g,l){var t=this;this.o=a;this.app=c;this.config=d;this.m=e;this.g=g;this.w=l;this.f=!1;this.b=new Ub;this.c=new M;this.u=d.transport.url;a=d.distribution;this.j={O:{reject:this.Ma.bind(this),resolve:this.Na.bind(this)},waitInterval:a.reliableMessages.waitInterval};this.identification=b.identification;this.m.bind([6,8],function(){return t.pa});this.h=new mb([m[0]],this.Aa.bind(this));this.a=new uc(f,this.h,d.identification.visitTimeSpan);(this.storeEnabled=a.persistence.storeEnabled)&&
this.a.startSession(this.identification.L);this.pa()}h=vc.prototype;
h.W=function(a,b){var c;c={data:a};var d={};if(b.reliable&&w(this.b,b.id,d)){if(c=d.K,0>--c.retries)return this.app.ia()}else c={message:c,metrics:b,retries:this.config.distribution.reliableMessages.retries,M:{name:b.type,enabled:b.type===m[0]}},S(this.b,b.id,c);d=this.u+"?t="+c.metrics.type+"&p="+this.o+"&2="+this.identification.Y+"&v=1.3.61";wc(this,c,d);xc(this,c,d)&&this.storeEnabled&&(c.metrics.type===m[0]?this.a.stopSession(this.identification.L):this.a.extendSession(this.identification.L,this.config.identification.visitTimeSpan))};
function xc(a,b,c){var d=a.g.a[b.metrics.type](a.j);return a.f?(d.send(c,b),!0):!1}h.Aa=function(a,b){var c;c={};var d=a.message.data,e=d.data;"string"===typeof e&&(d.data=this.c.b(e));w(this.b,d.id,c)?c=c.K:(c={message:d,metrics:{id:0,type:a.message.name,reliable:!1},retries:0,M:{w:b,locator:a.locator,result:a,retries:this.config.distribution.persistence.dispatchRetries}},S(this.b,d.id,c));xc(this,c,a.message.url)||b.reject(a)};
function wc(a,b,c){if(b.M.enabled&&!b.M.locator&&a.storeEnabled){var d=a.c.a(b.message.data);b.M.locator=a.a.storeMessage({url:c,data:{id:Date.now(),data:d},name:b.metrics.type,sid:a.identification.L},function(){},!1,!1)}}h.Na=function(a){var b=a.M;b.w&&b.w.resolve(b.result);b.locator&&this.a.removeMessage(b.locator);a.metrics&&this.w.resolve(a.metrics)};h.Ma=function(a){var b=a.M;b.w&&(0<--b.retries?b.w.defer(b.result):b.w.reject(b.result));a.metrics&&this.w.reject(a.metrics)};
h.pa=function(){(this.h.isAvailable=(this.f=navigator.onLine)&&this.config.distribution.persistence.dispatchEnabled)&&this.a.sendMessages()};function yc(a,b,c,d){void 0===c&&(c=document);void 0===d&&(d=window);z.call(this,b);this.g=a;this.c=c;this.J=d;this.a=13;this.u=this.j.bind(this);this.b=0;this.g.bind([2,3],this.u);this.j()}k(yc,z);
yc.prototype.j=function(){var a=this.c.documentElement,b=this.c.body,a=((this.J.innerHeight||a.clientHeight||b.clientHeight)+(a.scrollTop||b.scrollTop))/(a.scrollHeight||b.scrollHeight)*100,a=Math.abs(Math.round(Math.min(100,a)));this.b=Math.max(a,this.b);100===this.b&&ua(this.g,[2,3],this.u)};yc.prototype.i=function(){return this.b};function X(a,b){z.call(this,b);this.b=a;this.c=0;this.a=14;this.b.bind([7],this.u.bind(this));this.b.bind([9],this.g.bind(this))}k(X,z);
X.prototype.g=function(a){this.j=a.target};X.prototype.u=function(a){this.j===a.target&&this.c++};X.prototype.i=function(){return this.c};var Y;
function zc(){return Na({metrics:{inactivityTime:2E4,interestInterval:12E3,maxFetchInterval:5E3,touchMouseIgnoreTime:500,goalOrientedCloseInterval:2E3,enableOptionalEndMetrics:!0,maxPageTagLength:50,pageTagRedundancy:3,maxPageTagsPerPage:10,maxTagsOnEnd:3,providers:"TagsMetric BrowserMetric EventIdsMetric TimeOnPageMetric ScrollReachMetric AppLoadTimeMetric InputMethodMetric JSErrorCountMetric GoalOrientedMetric DiscardedTagsMetric FirstPageviewMetric ViewPortWidthMetric AdobeLegacyIdMetric ViewPortHeightMetric NumberOfClicksMetric BrowserVersionMetric LackOfInterestMetric AttentionSplitMetric ClientTimeStampMetric ResolutionWidthMetric NavigationStartMetric ResolutionHeightMetric CarelessScrollingMetric ScreenOrientationMetric GoogleAnalyticsIdMetric AdobeMarketingCloudIdMetric DurationSinceLastVisitMetric EngagementTimeAggregatorMetric".split(" ")},identification:{expirationDays:365,
visitTimeSpan:18E5,integrationMessageFormat:"CT2MappingTag_{0}_{1}_{2}_{3}",integrationMethod:function(){return self.ClickTaleEvent}},transport:{preChannel:"pre",mainChannel:"main",terminalChannel:"terminal",url:"https://conductor.clicktale.net/monitor",xhrTimeout:2E3,disableImageChannel:!1},distribution:{reliableMessages:{retries:2,waitInterval:1E3},persistence:{storeEnabled:!0,dispatchRetries:3,dispatchEnabled:!0}},onEnd:{useOnBeforeUnload:!1}},self.ClickTaleMonitor.Settings.config)}
function Ac(a,b){this.a={};var c=a.transport,d={};d[m[3]]=c.preChannel;d[m[1]]=d[m[2]]=c.mainChannel;d[m[0]]=c.terminalChannel;for(var e in d)this.a[e]=bc(b,""+d[e])}function Bc(){F.apply(this,arguments);this.a=30}k(Bc,F);Bc.prototype.i=function(){return self.innerHeight|0};function Cc(a,b){for(var c=1;c<arguments.length;c++);var d=Array.prototype.slice.call(arguments,1);return a.replace(/\{(\d+)\}/g,function(a,b){return d[b]})}function Dc(){F.apply(this,arguments);this.a=17}k(Dc,F);
Dc.prototype.i=function(){return screen.height};function Z(a,b,c,d){var e=this;this.b=a;this.o=b;this.c=this.m=null;this.a=!1;this.c=c||self.location;this.m=d||document.referrer;var f=!!c;Ec(this,function(){Fc(e,f)&&e.start(f)})}var Gc;h=Z.prototype;h.na=function(){return Gc||(Gc=D())};h.oa=function(){return this.b};function Ec(a,b){a.a||"file:"===location.protocol||b()}
h.start=function(a){var b=this,c=self.ClickTaleGlobal;c&&Hc("onstarting");var d=this.l,e=d.resolve("Disposer");this.a=!0;d.resolve("EventListenerHub");d.resolve("MetricsReader");d.resolve("DistributionService");e.a=d.resolve("MetricAggregator");this.o&&this.o(this);c&&(c=function(){var a=Y||(Y=zc()),c=a.identification.integrationMethod(),a=a.identification.integrationMessageFormat,e=d.resolve("IdentificationService").identification,a=Cc(a,b.b,e.Y,e.ka,e.L);c(a)},ClickTaleGlobal.scripts.integration.onReady(c),
a&&c(),Hc("onstarted"))};function Hc(a){var b=ClickTaleGlobal.diagnostics;a=(b=b&&b.monitor)&&b[a];"function"==typeof a&&a()}
function Fc(a,b){var c=Y||(Y=zc()),d=new ya,e=d.userAgent.supports.sendBeacon?pb:c.transport.disableImageChannel?Pb:rb;if(d.userAgent.supports.Ba){var f=new T;a.l=f;a.h=new N(c);a.f=new ic(c,[new ra,new Mb]);var g=function(){return f.resolve("EventListenerHub")};Ic(a,c,g,d,b);cc(U(f,"IdMetric",function(a,b){return new ca(b)}));$b(f,null,d);Jc(a,e,c);U(f,"ChannelFactory",function(){return new Ac(c,f)});U(f,"IdGenerator",function(){return new db});U(f,"MetricsPromise",function(){return new Jb});U(f,
"CookiesService",function(){return new oc});U(f,"CookieSerializer",function(){return new Ga});U(f,"VisitService",function(){return new jb(c)});$b(f,"EventIdsMetric",a.h);$b(f,"TagsMetric",a.f);U(f,"EventListenerHub",function(){return new W});U(f,"NavigationStartTimerEventHub",function(){return new mc([c.metrics.interestInterval])});U(f,"AttentionSplitMetric",function(a){return new Nb(a.resolve("ScrollyBlocksProvider"),c)});U(f,"CarelessScrollingMetric",function(a){return new C(a.resolve("ScrollyBlocksProvider"),
c)});U(f,"ScrollyBlocksProvider",function(){return new Ca(g(),d.userAgent,self)});U(f,"Disposer",function(b){return new Za(g(),b,c,a)}).C=1;U(f,"PeriodicalNotifierRule",function(b){return new V(g(),c,a,b.resolve("MetricsPromise"))});U(f,"IdentificationService",function(a){return new Ta(a.resolve("IdGenerator"),a.resolve("CookiesService"),c,a.resolve("VisitService"),a.resolve("CookieSerializer"),b)});U(f,"LocalStorageProvider",function(){return new ClickTaleGlobal.persistence.LocalStorageProvider});
U(f,"WindowNameProvider",function(){return new ClickTaleGlobal.persistence.WindowNameProvider});U(f,"PersistenceManager",function(a){return new ClickTaleGlobal.persistence.PersistenceManager([a.resolve("LocalStorageProvider"),a.resolve("WindowNameProvider")])});U(f,"DistributionService",function(b){return new vc(a.b,b.resolve("IdentificationService"),a,c,g(),b.resolve("PersistenceManager"),b.resolve("ChannelFactory"),b.resolve("MetricsPromise"))});U(f,"MetricAggregator",function(a){var b=f.resolve("MetricsPromise"),
d=c.metrics.providers.map(function(b){return a.resolve(b)}).concat([a.resolve("VersionMetric"),a.resolve("LocationMetric"),a.resolve("ProjectIdMetric"),a.resolve("DocumentReferrerMetric"),a.resolve("VisitIdentificationMetric"),a.resolve("DOMContentLoadedTimeMetric"),a.resolve("VisitorIdentificationMetric"),a.resolve("PageViewIdentificationMetric")]);return new da(d,c,bc(a,"IdMetric"),b)});U(f,"MetricsReader",function(a){return new gc(a.resolve("EngagementTimeAggregatorMetric"),[a.resolve("EventIdsMetric"),
a.resolve("TagsMetric"),a.resolve("PeriodicalNotifierRule")],g(),a.resolve("MetricAggregator"),a.resolve("DistributionService"),a.resolve("IdentificationService"))});return!0}bb(e,c,a.b,a);return!1}
function Ic(a,b,c,d,e){function f(){return a.l.resolve("NavigationStartTimerEventHub")}function g(){return a.l.resolve("IdentificationService")}var l=Kc(e);[["VersionMetric",function(){return new zb}],["AppLoadTimeMetric",function(){return new vb(a)}],["ViewPortWidthMetric",function(){return new wb}],["AdobeLegacyIdMetric",function(){return new Ab}],["ViewPortHeightMetric",function(){return new Bc}],["BrowserMetric",function(){return new sb(d)}],["ResolutionWidthMetric",function(){return new Fb}],
["ClientTimeStampMetric",function(){return new ob}],["ProjectIdMetric",function(){return new Gb(a.b)}],["ResolutionHeightMetric",function(){return new Dc}],["GoogleAnalyticsIdMetric",function(){return new Ja}],["LocationMetric",function(){return new u(a.c,self)}],["NavigationStartMetric",function(){return new Ib(l)}],["AdobeMarketingCloudIdMetric",function(){return new yb}],["BrowserVersionMetric",function(){return new qb(d)}],["DocumentReferrerMetric",function(){return new lb(a.m)}],["DOMContentLoadedTimeMetric",
function(){return new nb(l)}],["ScreenOrientationMetric",function(){return new Eb(d.userAgent)}],["ScrollReachMetric",function(){return new yc(c(),b)}],["JSErrorCountMetric",function(){return new B(c(),b)}],["NumberOfClicksMetric",function(){return new X(c(),b)}],["TimeOnPageMetric",function(){return new Db(c(),l)}],["FirstPageviewMetric",function(){return new cb(g())}],["InputMethodMetric",function(){return new E(c(),b)}],["VisitIdentificationMetric",function(){return new Qb(g())}],["VisitorIdentificationMetric",
function(){return new ub(g())}],["DurationSinceLastVisitMetric",function(){return new kb(g())}],["PageViewIdentificationMetric",function(){return new Hb(g())}],["EngagementTimeAggregatorMetric",function(){return new eb(c())}],["GoalOrientedMetric",function(){return new $a(c(),f(),b)}],["LackOfInterestMetric",function(){return new x(c(),f(),b)}],["DiscardedTagsMetric",function(){return new oa(a.f)}]].forEach(function(b){return Zb(a.l,b[0],null,b[1])})}
function Kc(a){var b=(new Date).getTime();return self.performance&&!a&&(a=performance.timing,!isNaN(a.navigationStart)&&18E5>b-a.navigationStart)?a:{domContentLoadedEventEnd:b,navigationStart:Z.a||b}}h.ia=function(){this.dispose(!0)};h.va=function(){this.dispose(!1,!0)};h.dispose=function(a,b){this.a&&(this.l.resolve("Disposer").dispose(a,b),Y=null,delete Z.a)};h.la=function(){this.a&&(this.a=!1,this.g&&this.g())};h.La=function(a){this.g=a};h.fa=function(){return this.a};
function Jc(a,b,c){var d=new M,e=c.transport;U(a.l,e.terminalChannel,function(c,g){return new b(g,a,d,e.xhrTimeout)}).C=1;cc(U(a.l,e.mainChannel,function(b,c){return new J(c,a,new Ka,e.xhrTimeout)})).C=1;cc(U(a.l,e.preChannel,function(c,g){return new b(g,a,d,e.xhrTimeout)})).C=1}h.ta=function(a){var b=this.h;-1===b.b.indexOf(a)&&(b.b.push(a),b.c&&b.g())};h.$=function(a,b,c){jc(this.f,a,b,c)};h.ua=function(a,b,c){this.$(a,b,c)};h.ya=function(a,b,c){this.$(a,b,c)};
h.da=function(){return this.l?this.l.resolve("MetricAggregator").da():""};Z.a=self.a||(new Date).getTime();Z.prototype.stop=Z.prototype.la;Z.prototype.onStop=Z.prototype.La;Z.prototype.addTag=Z.prototype.ua;Z.prototype.dispose=Z.prototype.dispose;Z.prototype.getState=Z.prototype.da;Z.prototype.shutdown=Z.prototype.ia;Z.prototype.endVisit=Z.prototype.va;Z.prototype.addEvent=Z.prototype.ta;Z.prototype.addPageTag=Z.prototype.ya;Z.prototype.addTagIntro=Z.prototype.$;Z.prototype.getLoadTime=Z.prototype.na;
Z.prototype.isMonitoring=Z.prototype.fa;Z.prototype.getProjectId=Z.prototype.oa;var Lc="object"===typeof module&&"object"===typeof module.exports,ClickTaleMonitor=(Lc?module.exports.ClickTaleMonitor:self.ClickTaleMonitor)||{};ClickTaleMonitor.App=Z;Lc?module.exports=ClickTaleMonitor:self.ClickTaleMonitor=ClickTaleMonitor;ClickTaleMonitor.version="1.3.61";if (self.ClickTaleMonitor && self.ClickTaleMonitor.Settings) { self.ClickTaleMonitor.Settings.onReady(); }}.call({});
